### ISSUE TITLE
Can't post new idea

### ISSUE THREAD

**Issue by sinisakrisan** [jomsocial/JSVoice#3]
Just try to post new idea using all default settings

It will be stuck here
<img width="1082" alt="screenshot 2015-09-30 10 19 47" src="https://cloud.githubusercontent.com/assets/3237973/10182937/df723618-675c-11e5-9220-977942fb0be0.png">

**Comment by lexxarious** [comment]
This is caused by captcha, i have removed the visual settings for captcha in the backend.
